import type { Metadata } from "next";
import { Inria_Sans } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";
import Head from "next/head";

const inria = Inria_Sans({
    subsets: ["latin"],
    weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Chikinmos | Korean Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={inria.className}>
        <Navbar />
        {children}
      
      </body>
    </html>
  );
}
